export const Actiontypes = {
  SET_NEW_PRODUCTS: 'SET_NEW_PRODUCTS',
  SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
  SET_ACTIVE_SIDEBAR: 'SET_ACTIVE_SIDEBAR',
  SET_ALL_CATEGORY: 'SET_ALL_CATEGORY',
  SET_PRODUCTS_BY_CATEGORY: 'SET_PRODUCTS_BY_CATEGORY',
  SET_PRODUCT_BY_ID: 'SET_PRODUCT_BY_ID',
};
